### ISSUE TITLE
Garden Cloche rf/t Usage 

### ISSUE THREAD

**Issue by tcanfield123** [AllTheMods/ATM3-Lite#11]
Was it deliberate changing the garden cloche (immersive engineering) to using 80 rf/t instead of 8?  10 times what the default mod dictates?

**Comment by OrdinatorStouff** [comment]
This may or may not have been deliberate. It's possible the pack "borrowed" configs from ATM3 or also possible that at the time the config file was auto-generated the mod default was 80. If the mod default changes later they don't retroactively regenerate config settings.  
  
That being said, 80 still seems pretty reasonable considering how useful the cloche is...

**Comment by tcanfield123** [comment]
The mod default has been 8 rf/t for as long as I've been playing Minecraft.  80 does still seem reasonable, I was just wondering if it was on purpose.
