### ISSUE TITLE
Console errors and sync issues.

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM3-Lite#12]
Me and 3 of my friends started a new world on a server I created. Ever since the start of the server we have been getting messages spamming the console that I am not entirely sure how to fix. The console repeatedly says "*username* out of sync, resyncing! error = 0.0" or, "*username* tried to move into a block!". This typically happens when we run or jump around and especially when using the tinkers' construct slime sling item. If anybody could tell me how to fix this or explain the root of the problem, it would be greatly appreciated! I'll leave a screenshot of my server logs attached. Thanks
![error messages](https://user-images.githubusercontent.com/40781386/42195860-0a67a366-7e49-11e8-92f9-7a36add4db21.PNG)

**Comment by FallenEagle1** [comment]
Closing for now, reopen if this still occurs with newer versions of the pack.
