### ISSUE TITLE
Making Ethetic Green Block, AA

### ISSUE THREAD

**Issue by StrommKral** [AllTheMods/ATM3-Lite#13]
Chisel a block of Quartz into Chiseled Quartz and toss in front of an Atomic Reconstructor should produce the Green Block. It does not, it gives you the regular Ethetic block. The Id of the chiseled block is correct.

**Comment by SpeedSlider** [comment]
This issue is resolved by manually updating to the latest release version of Actual Addition. The current version included in the pack is a beta version.

**Comment by FallenEagle1** [comment]
Confirmed working in the test pack with updated mods.
