### ISSUE TITLE
Lonsdaleite Crystal Enviromental Tech

### ISSUE THREAD

**Issue by StrommKral** [AllTheMods/ATM3-Lite#14]
There is no JEI entry for this, in ATM3 you get it from the void ore miner tier 1-6. It's used to make the modifiers for the different miners, and the nanobot. I'm into the T2 miner now and I have not gotten any after 20 hours in game running the miner. Just wondering if it's disabled for the Lite pack?

**Comment by FallenEagle1** [comment]
This is fixed and working now in my test pack for updating.
