### ISSUE TITLE
Crash when crafting Advanced Solar Panel (crash when rendering item)

### ISSUE THREAD

**Issue by BennehR** [AllTheMods/ATM3-Lite#15]
I crafted a single Advanced Solar Panel (ASP) from Mekanism and placed it in the world, when crafting a second one the game is crashing to desktop.

This is when i use shift+click on the helper icon to move the items from inventory to crafting station (tinkers)

[crash-2018-07-19_15.46.19-client.txt](https://github.com/AllTheMods/ATM3-Lite/files/2210499/crash-2018-07-19_15.46.19-client.txt)
[crash-2018-07-19_15.52.17-client.txt](https://github.com/AllTheMods/ATM3-Lite/files/2210500/crash-2018-07-19_15.52.17-client.txt)

Private server, running V3.0.1
Optifine added to my client side

**Comment by FallenEagle1** [comment]
Known issue with the tinkers crafting table. It doesn't seem to always be consistent, but one way around this is to disable tinkers rendering in the config file. Should be line 7 in the config, ` B:renderInventoryInWorld=true`
