### ISSUE TITLE
Massive Mod Glitch with 9 additinal mods that make all modpacks better (dimension+boss-spawning Render glitch)

### ISSUE THREAD

**Issue by CrasyFoxBoy** [AllTheMods/ATM3-Lite#16]
i have a massive bug when i have 9 extra mods added that makes all mod-packs better.

 

-bug 1: no matter what i do... i cant go to any dimension other than the nether, if i enter the end or even summon the wither, i crash and cant rejoin my mine-craft modded world

 

-bug 2: additionally when i go to the nether, my difficulty gets glitched in peaceful mode even when its locked until i restart forge completely

 

-bug 3:strange terrain glitch where sometime ill find massive lava pits in the mine-craft world as if someone set off a massive nuke. more like giant ravines?!

 

 

      -=mods=-

Chisls-and-bits

actual-music

apple-skin

A+game_Opti-Fine_1.12.2_HD_U_E15_MOD.jar

apple-core

deathquotes

pams-harvestcraft

Quark

+2

**Comment by Yoosk** [comment]
I am terribly sorry, but as you add additional mods to our modpack, i cant help you to fix bugs you introduced by doing that.

**Comment by CrasyFoxBoy** [comment]
i am very sorry if this annoys you, but it would help the modded community a bit 👍.

it would be nice if you added these extra mods to the mod-pack because many of these mods might actually make this mod-pack 10X better, even though this mod-pack is already awesome especially for lower end Computer devices!

                          <{here's the list but in much further details}>
**actual-music** allow music that doesn't suck really badly to play in minecraft which allows for some Epicness, lol.
https://minecraft.curseforge.com/projects/actualmusic?gameCategorySlug=mc-mods&projectID=266943

https://minecraft.curseforge.com/projects/fairy-tail-song-pack-for-actualmusic?gameCategorySlug=customization&projectID=267771

https://minecraft.curseforge.com/projects/pmdsky-song-pack-for-actualmusic?gameCategorySlug=customization&projectID=267512

**a-game-optifine** is an edit version of optifine which allow it to be played with forge, quite useful for me to get rid of inefficient particles and special effects, resulting in an fps boost. although most modders say to not insert optifine in forge Mod-pack "downloads"
{No Link Because I forgot where i got it}

**death-quotes** is a small but funny mod that adds quotes in chat above your death message, making dieing not so infuriating
https://minecraft.curseforge.com/projects/deathquotes-death-quotes?gameCategorySlug=mc-mods&projectID=253947

**quark** allow me to sit on stairs as if they where chairs and do emotes in-game for my videos i make, also has underground biomes such as lush underground biomes in jungles  and sandstone patches in desserts  also makes clay and andisite not such a hassle to find
https://minecraft.curseforge.com/projects/quark?gameCategorySlug=mc-mods&projectID=243121

i am into making beautiful terrain and farms, but the 5 grow-able plants in the game just doesn't cut it, **pams-harvestcraft** makes it possible to make amazing foods and awesome farms, also enables many foods to eat that is useful, making the start of the game a bit harder which i like because it makes the game last longer.
https://minecraft.curseforge.com/search?search=Pam%27s+HarvestCraft+

**chisels-and-bits** is a very  Awesome mod that allows me to make any Prop or small block i want that gives me more of a range of decor and props i want, making it a bit harder to decorate but also worth it.
https://minecraft.curseforge.com/projects/chisels-bits?gameCategorySlug=mc-mods&projectID=231095

**animania** is a laggy mod for me because of all the extra mobs but their cute, i wonder if there's a way to get that mod in without much of a hassle, _Such cute hamsters!!!_
https://minecraft.curseforge.com/projects/animania?gameCategorySlug=mc-mods&projectID=261199

last but definitely not least, the mod called "**(ANGRY PIXEL)The Between-lands**" a mod i always wanted to play, but all mod-packs that have it leave me at 1 fps when i run a world or if i put it in my mods folder, i cant enter the dimension... sometimes it even says "You are playing an unsupported modified version of the game" if that's the only mod in the mods folder.
https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod?gameCategorySlug=mc-mods&projectID=243363

**again... i am so Extremely Very sorry if i went overboard but i have a few friends that would like to see some of these mods such as chisels-and-bits, pams-harvestcraft, quark, and actual-music in the pack, i am just a kid but i know 
java-script code a little bit, so i am extremely sorry if this annoyed you. hope you think about it, or open a forum thread of yes or no choices to see what ratio of the mine-craft modded population wants these extra mods added to all-the-mod's-Lite.**

_i inserted the links to make finding the mods a bit easier._

**Comment by FallenEagle1** [comment]
A number of those mods are in the regular atm3 pack already. Atm3 lite is made with the idea that it is supposed to be a little less ram intensive. As for optifine, it is not allowed to be included in packs by default do to its permissions, but you are allowed to add it on your own.

**Comment by CrasyFoxBoy** [comment]
oh. I only sugjested these mods because these mods would be nice to have in All-the-mods-lite and many more people would enjoy the extra mods othor than then
 **The Between-lands**.

By the way, How many people have made a suggestion to add one of these mods to ATML?

also when i have **6 GB** of ram allocated to play this mod-pack with the mods i suggested,, i still can play for long times while starting out with **30%-46%** of the ram filled when i start to play

**Comment by BloodWorkXGaming** [comment]
Well, the lite version is planned to require far less memory, in the best
case it could even run with 3-4 GB.

So adding a lot of expensive mods doesn't help to achieve this goal.
If you have that much memory to spare maybe the full Atm3 might suit your
playstyle better?

CrasyFoxBoy <notifications@github.com> schrieb am Mo., 23. Juli 2018, 18:32:

**Comment by CrasyFoxBoy** [comment]
i get left with 1 fps when i play _default_ **all-the-mods-3**

i don't know why, but i just sometimes cant open _mine-craft_ with the default **all-the-mods-3**...

ill try though, if it doesn't work, ill report back to the normal ATM3 bug reporter.
