### ISSUE TITLE
Recipes are modified and broken during gameplay

### ISSUE THREAD

**Issue by IceMetalPunk** [AllTheMods/ATM3-Lite#17]
I'm not sure quite what's causing this, but it's a serious bug; here's what happens:

I have an EnderIO crafter set up to craft 9 Tiny Dry Rubber into 1 Dry Rubber, then output it to a Redstone Furnace for smelting. That works for a bit... but then suddenly, the Dry Rubber recipe seems to be completely removed for no reason. As in, the recipe (according to both the crafter and JEI) becomes 9 Dry Rubber equals nothing. (So more accurately, the recipe remains, but its result becomes empty.)

Everything works for about 5 to 7 minutes before this happens. I don't know if the problem is related to the Crafter, or something else, but it keeps happening, breaking my automation. It's almost as if the recipe registry is being mutated at runtime, but that shouldn't happen (or at least not in quite this way).

**Comment by sebi2306** [comment]
Have you tried other means of automatically crafting too, such as the Sequential Fabricator from Thermal Expansion?

**Comment by IceMetalPunk** [comment]
I have. They work fine. It's just the EnderIO crafter that seems to cause this issue.

**Comment by FallenEagle1** [comment]
Should be fixed in the updated versions of enderio.
