### ISSUE TITLE
dragon egg not dropping when the dragon is respawned

### ISSUE THREAD

**Issue by StrommKral** [AllTheMods/ATM3-Lite#18]
just what is says

**Comment by FallenEagle1** [comment]
Confirm this is happening with the test pack I have with updated mods.

**Comment by FallenEagle1** [comment]
This shows how much of the little vanilla mechanics I remember. Unless changed by a mod, the ender dragon does give any extra dragon eggs after the first one. So a mod would have to change that behavior, and looking through the modlist nothing jumps out at me that would change it. @StrommKral besides tech reborn, was there another use for the dragon eggs? If so, I might consider adding a recipe for them.

**Comment by StrommKral** [comment]
EU2 grid power is the first thing that comes to mind, without loading the pack that's all i can think of
ATM

**Comment by FallenEagle1** [comment]
Good point forgot about that. I should have a recipe fairly quick, I have one in mind already, unless you have thoughts on it as well.

**Comment by StrommKral** [comment]
it should at least include the crystals, for anything else that is up to you, as by the time your ready to re-spawn the dragon, killing it is trivial, so i wouldn't make it too hard

**Comment by FallenEagle1** [comment]
The silent gem crystals? Thats what I was thinking of. Will see about the rest of it.

**Comment by StrommKral** [comment]
no, the ones used to re-spawn the dragon, glass panes around a ghast tear? iirc. maybe those in the corners, and a netherstar in the middle?

**Comment by StrommKral** [comment]
i see its a bit different in lite, takes a tear, eye and 7 glass blocks, so 4 of those and a nether star?

**Comment by StrommKral** [comment]
I see no other use for the egg in Lite, other than the Mill for EU2. not sure what your thinking about tech reborn uses the egg for

**Comment by FallenEagle1** [comment]
There is the siphon that allows you to produce a little bit of power from the dragon egg. Works similar to the mill from EU2, just does FE instead of GP

**Comment by FallenEagle1** [comment]
Dragon egg recipe is added, shouldn't be too bad to get.

**Comment by FallenEagle1** [comment]
Fixed in dev
