### ISSUE TITLE
Ethetic Green Blocks

### ISSUE THREAD

**Issue by Grand-Trizmo** [AllTheMods/ATM3-Lite#19]
recipe doesnt work for the blocks im thinking the ore data for the different quartz blocks is breaking it
![Image of Recipe](https://i.triz.moe/1534193429.png)
Gif of the recipe it outputs regular Ethetic Blocks
https://i.triz.moe/1534193535.gif

**Comment by Sleeeper** [comment]
never had a problem with it, uses chiseled quartz blocks at the left

**Comment by Grand-Trizmo** [comment]
thats what i was using in the gif i put

**Comment by sebi2306** [comment]
duplicate of #13
