### ISSUE TITLE
Mods only client side

### ISSUE THREAD

**Issue by BestFraz** [AllTheMods/ATM3-Lite#20]
I have managed to create a server and my friends can join. However, game changing mods, ie. Mekanism and Tinkers and JEI, cannot be used. Their items cannot be crafted. Only mini maps and tool tips etc... are usable. 
    When looking at the log I see that the mods have been disabled due to being client side only. How can I fix this?

**Comment by martmists** [comment]
how did you install the server?

**Comment by FallenEagle1** [comment]
Closing due to no info since August.
