### ISSUE TITLE
Integred Tunnels Inventory Reader with Refined Storage Interface Connection

### ISSUE THREAD

**Issue by TheDoctorOne** [AllTheMods/ATM3-Lite#22]
That cause huge lag. It may not seem effecting TPS but it definitly lags the server. The reason might be the Integred Tunnels can't handle huge item databases. I guess, It tries to scan everysingle item(while extracting) in storage.

Hope information helps. Good work! Keep it up!

**Comment by FallenEagle1** [comment]
There have been some improvements to the mod since then. Can reopen if this still occurs with the newer versions.
