### ISSUE TITLE
Error Launching server 

### ISSUE THREAD

**Issue by Ks1999** [AllTheMods/ATM3-Lite#26]
When trying to launch the server start bat.file, it doesn't work and sends an error saying 
"Can't find valid java version installed"

**Comment by FallenEagle1** [comment]
Usually this shows up when you either have 32 bit java, or are trying to run on Java 9/10. The java version needs to be 64 bit java 8.

**Comment by Ks1999** [comment]
> Usually this shows up when you either have 32 bit java, or are trying to run on Java 9/10. The java version needs to be 64 bit java 8.
This is the java version that I am using currently.
Got it from here 
https://www.java.com/en/download/
Version 8 Update 181
Release date July 17, 2018

**Comment by Ks1999** [comment]
> Usually this shows up when you either have 32 bit java, or are trying to run on Java 9/10. The java version needs to be 64 bit java 8.

**Comment by Ks1999** [comment]
This is the java version that I am using currently.
Got it from here 
https://www.java.com/en/download/
Version 8 Update 181
Release date July 17, 2018

**Comment by FallenEagle1** [comment]
If you type into a command prompt `java -version` what does it say (exactly)?

**Comment by Ks1999** [comment]
C:\Users\Umara>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) Client VM (build 25.181-b13, mixed mode)

**Comment by FallenEagle1** [comment]
Annnd that would be 32 bit java.
https://www.java.com/en/download/manual.jsp
Grab the one from here that is 64 bit.
