### ISSUE TITLE
Tech Reborn ores are appearing as well as Thermal ore gen.

### ISSUE THREAD

**Issue by Boomflex** [AllTheMods/ATM3-Lite#27]
Hi guys,

Currently running a slightly modified (self-updated version - not sure if this has any bearing) of ATM3Lite and I have noticed a few cross over ores such as Copper/Tin...

I have checked the Configs and either Tech Reborn reset its configs, or "we" never did it originally?

Might be on me, but the wife asked why she had 2 different "orange ores"... 

Cheers boys <3

**Comment by FallenEagle1** [comment]
No, I think its something I changed when refreshing the configs a while back. Sped over the particular changes too quick and enabled them.

**Comment by FallenEagle1** [comment]
Should be fixed in the 3.0.3 Update that is live now.

**Comment by Boomflex** [comment]
<3
