### ISSUE TITLE
Swap out Fast Leaf Decay for Quick Leaf Decay

### ISSUE THREAD

**Issue by Boomflex** [AllTheMods/ATM3-Lite#3]
wsspad on Reddit recommended.

**Comment by MrMetric** [comment]
Context for anyone who finds this while searching for info on Fast Leaf Decay and Quick Leaf Decay: https://old.reddit.com/r/feedthebeast/comments/753hdl/do_you_want_to_play_a_112x_kitchen_sink_pack_but/do3cnmt/
