### ISSUE TITLE
Copper Tin and Lead Ore spawning from 2 different mods in Mining Dimension

### ISSUE THREAD

**Issue by AlanBTG** [AllTheMods/ATM3-Lite#4]
Version 2.0
Copper, Tin and Lead Ore from both Thermal Foundation and Industrial Craft spawns in the world.

**Comment by Boomflex** [comment]
According to the IC2 config Copper, Tin and Lead are disabled...

`[worldgen]
; Enable generation of rubber trees in the world.
rubberTree = true
; Enable generation of copper in the world.
copperOre = false
; Enable generation of tin in the world.
tinOre = false
; Enable generation of uranium in the world.
uraniumOre = true
; Enable generation of Lead in the world.
leadOre = false`

**Comment by Boomflex** [comment]
I have restarted 5 different worlds and used the World Stripper mod and I can confirm there are no IC2 ores that shouldn't be there.

https://i.imgur.com/4ZFaek0.jpg

So closing this for now.

**Comment by AlanBTG** [comment]
Did you try it on the mining dimension from Aroma's Dimension? I should have specified that sorry.

**Comment by Boomflex** [comment]
Tried on Mining Dimension.

0 IC2 ores other than the uniques.

**Comment by AlanBTG** [comment]
Updated to version 2.0a and tried World Stripper on a new world.
No more IC2 ores spawning. I'll have to delete the mining dimension and purge non-base chunks to get rid of most of them.
But I found a new Issue now, Bauxite Ore isn't spawning in both version.

**Comment by Boomflex** [comment]
Do you need Bauxite if Aluminium from Thermal is there?

**Comment by AlanBTG** [comment]
My bad I mixed it up for Copper ore when I used World Stripper.
