### ISSUE TITLE
Nether portal disables Extra Utilities 2 flight rings

### ISSUE THREAD

**Issue by tbfox** [AllTheMods/ATM3-Lite#41]
Quite simply every time I go through a nether portal my ring disables and I cannot fly. The simple work around is swapping bauble slots which for some reason enables flight again. Also I am positive the correct power grid power generation chunks are loaded because the ring still works in the nether after swapping bauble slots. Also shift clicking into my inventory and back into the bauble slot does not work even if it is the other ring bauble slot.

**Comment by RedstoneMaster256** [comment]
Pack devs often can't do much about mod bugs. Better to report to the Extra Utilities 2 dev and see if they can fix it, push an update, then have ATM3 update to that version.

**Comment by Yamza** [comment]
Pretty much as above. I would suggest reporting it to EXU2, but development on that mod has been dead for months so I wouldn't expect a fix on that.

**Comment by Sleeeper** [comment]
It happens on any dimension change not just nether portal. just drop ring away or put into chest and pick up back to force update the effect. should be able to fly again.
