### ISSUE TITLE
Having an Issue when trying to open ATM 3 Lite

### ISSUE THREAD

**Issue by Gabbertay** [AllTheMods/ATM3-Lite#42]
![Crash](https://user-images.githubusercontent.com/59539691/71785809-2b0aff00-2fd2-11ea-8cff-488145477f4b.PNG)

I've looked everywhere and couldn't find a fix for it.

[ATM3LITE-Crash.txt](https://github.com/AllTheMods/ATM3-Lite/files/4024030/ATM3LITE-Crash.txt)

**Comment by Gabbertay** [comment]
[ATM3LITE-Crash.txt](https://github.com/AllTheMods/ATM3-Lite/files/4024028/ATM3LITE-Crash.txt)

**Comment by whatthedrunk** [comment]
Let me know if you have the issue with v3.1.2
