### ISSUE TITLE
Launching Error

### ISSUE THREAD

**Issue by Gideon-the-Bard** [AllTheMods/ATM3-Lite#44]
Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\User\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

**Comment by whatthedrunk** [comment]
Let me know if you have the issue with v3.1.2
