### ISSUE TITLE
Server start stops part way through

### ISSUE THREAD

**Issue by Ix-risor** [AllTheMods/ATM3-Lite#45]
I have downloaded and unzipped the server pack to a new folder in my D drive. I run ServerStart.bat, which seems to run fine until betterfps checks for an update. Log below:
[2020-05-21-3.log](https://github.com/AllTheMods/ATM3-Lite/files/4665067/2020-05-21-3.log)
I restarted my computer, but it had no effect on the issue.

**Comment by whatthedrunk** [comment]
Let me know if you have the issue with v3.1.2
