### ISSUE TITLE
[Suggestion] Disabling Platinum Ore from the Envirominer or adding it to the World Gen.

### ISSUE THREAD

**Issue by AlanBTG** [AllTheMods/ATM3-Lite#6]
On 2.0 Platinum Ore doesn't spawn since thats the default for Thermal Expansion, you are supposed to get it by pulverizing Nickel Ore. Could we have it disabled on the Envirominer or add it to the world gen to fix this inconsistency?

**Comment by OrdinatorStouff** [comment]
@Boomflex all you should need to do is just delete the enviro tech configs/jsons and let them re-generate. Test to confirm though since I'm not 100% but unless you've made personalizations to the loot tables I think this is the best way to re-generate based on current worldgen.

**Comment by Boomflex** [comment]
Updated in 2.1
